# Generated by Django 4.2.1 on 2023-05-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Форма пользователя', 'verbose_name_plural': 'Формы пользователей'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='course',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack'), ('android', 'Android'), ('iOS', 'iOS'), ('UX/Ui design', 'UX/UI-дизайн'), ('OP', 'Основы программирования'), ('Project_manager', 'Менеджер проектов'), ('None', 'Я еще не определился')], max_length=100, verbose_name='Выбор направления'),
        ),
    ]
