# Generated by Django 4.2.1 on 2023-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Логотип сайта')),
                ('phone', models.CharField(max_length=255, verbose_name='Тел.номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('locate', models.CharField(max_length=255, verbose_name='Адрес')),
                ('facebook', models.URLField(verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(verbose_name='Ссылка на Instagram')),
                ('youtube', models.URLField(verbose_name='Ссылка на Youtube')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройка',
            },
        ),
    ]
