# Generated by Django 4.2.1 on 2023-05-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('course_for', models.CharField(max_length=50, verbose_name='Курсы для:')),
                ('is_laptop', models.BooleanField(verbose_name='Наличие ноутбука')),
                ('course', models.CharField(max_length=100, verbose_name='Выбор направления')),
            ],
        ),
    ]
