# Generated by Django 4.2.1 on 2023-05-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_courseschoicemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschoicemodel',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
